unbind-key C-b
set -g prefix C-k
set -g history-limit 10000
set -sg escape-time 500
bind-key C-k send-prefix
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

set-window-option -g mode-keys vi
set -g mouse on

set -g default-terminal tmux-256color
set -as terminal-features ",xterm-256color:RGB"

# Claude Code
# https://code.claude.com/docs/ja/terminal-config#configure-tmux
set -g allow-passthrough on
set -s extended-keys on
set -as terminal-features 'xterm*:extkeys'
